apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: room-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: room-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: room_db
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi